server:
  port: 7793
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://112.74.16.186:8080/eureka/
spring:
  application:
    name: eurekaOne
